[package]
name = "clickfix-shield"
version = "0.2.0"
edition = "2021"

[dependencies]
clipboard-win = "4"
regex = "1"
once_cell = "1"
tao = "0.26"
windows = { version = "0.57", features = [
  "Win32_UI_WindowsAndMessaging",
  "Win32_Foundation",
  "Win32_UI_Shell",
  "Win32_System_Threading"
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
time = { version = "0.3", features = ["macros", "formatting"] }
tray-icon = "0.14"

[build-dependencies]
winres = "0.1"